# Repeatome of the Brachypodium model grasses

This repository contains data and protocols used and produced in the study titled "Expansions and contractions of repetitive DNA elements reveal contrasting evolutionary responses to the polyploid genome shock hypothesis in Brachypodium model grasses" conducted by María Ángeles Decena, Rubén Sancho, Luis A. Inda, Ernesto Pérez-Collazos and Pilar Catalán

Each of these folders contains the input files necessary for the analyses performed, as well as the output files generated by them. A specific "Readme" file for each analysis is included in the folders.
